FROM node:14

WORKDIR /usr/src/app

ENV NODE_OPTIONS=--max_old_space_size=16384

RUN apk update && apk add curl

COPY package*.json ./

RUN npm install
RUN npm ci --only=production

COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]
