FROM node:lts-alpine

# Install python and other dependencies
RUN apk --no-cache add python3 make g++ \
    && ln -sf python3 /usr/bin/python

WORKDIR /usr/src/app

ENV NODE_OPTIONS=--max_old_space_size=16384

RUN apk update && apk add curl

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3200
CMD [ "npm", "start" ]
